name       : haskell-hsyaml
version    : 0.1.2.0
release    : 1
source     :
    - https://hackage.haskell.org/package/HsYAML-0.1.2.0/HsYAML-0.1.2.0.tar.gz : a45cf71fd793211bcfe7e303369879bde2d6f73a12d51e89d9a91413247452dd
license    : GPL-2.0-or-later
component  : programming.haskell
summary    : Pure Haskell YAML 1.2 processor
description: |
    HsYAML is a YAML 1.2 processor, i.e. a library for parsing and serializing YAML documents.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
